:doctype: book

= Trigger Infrastructure Provisioning and automation from Terraform Enterprise - Part 2

In this challenge you will learn how to trigger infrastructure provisioning and automation from Terraform Enterprise.

There are a number of prerequisites that you will need to complete before you can start this lab.

In this part we will continue the prerequisites and put the final touches on the Terraform Enterprise Workspace.

* Terraform Enterprise
** Cloning a GitHub repository to your account
** Create a Terraform Enterprise Workspace that used Version Control System (VCS) to store the Terraform code





In this challenge you will learn how to bring in HashiCorp Vault Enterprise to your automation pipeline.

[#task1]
== What is HashiCorp Vault Enterprise?

HashiCorp Vault Enterprise is a tool that allows you to manage secrets and other sensitive data.

[#task2]
== How to bring in HashiCorp Vault Enterprise to your automation pipeline

[#task3]
== How to use HashiCorp Vault Enterprise in your automation pipeline